### model
model_name_or_path: {model_path}
image_resolution: {image_resolution} # 262144 # 512*512 检查最大
video_resolution: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_config.json   # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: {dataset} # ,identity,alpaca_en_demo
template: {template}
cutoff_len: {cutoff_len}
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: {output_path}
logging_steps: 2
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: {per_device_train_batch_size}
gradient_accumulation_steps: {gradient_accumulation_steps}
learning_rate: {lr}
num_train_epochs: {epoch}
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

report_to: wandb
run_name: {wandb_run_name} # 可选